### ISSUE TITLE
[FATAL] Device could not be opened!

### ISSUE THREAD

**Issue by grigio** [casept/hyperhotp#1] opened 2021-06-07 20:24 UTC
Hi, thanks for your sw, I tried to run it but I get this error. It works as virtual keyboard but I can't reprogram it

```
./hyperfido help
[FATAL] Device could not be opened! ...
# cat /dev/hidraw3
888888
```

**Comment by casept** [comment] 2021-06-07 20:49
Hi,
I'm glad that other people find this useful!

Could you send me the output of `lsusb -v`, just to check how your device might differ from mine?

Also, what's the full output of the program when compiled in debug mode (`make clean && cmake -DCMAKE_BUILD_TYPE=Debug .. && make`)? Setting that flag enables additional debug output.

Finally, what's your environment? The problem is probably caused by my code, hacked-together and undertested as it is, but having more info wouldn't hurt.

If all that doesn't help track it down, I'll improve the code to actually log what error exactly libusb returned and ask you to try that version (was too lazy to do it earlier, but now that people actually try to use this it'd probably be helpful).

**Comment by grigio** [comment] 2021-06-07 20:56
Sorry my fault, I was trying to pass the device in docker but it seems it isn't enough.. it works as virtual keyboard but not completly. It seems to work natively.

Can you make example of "./hyperhotp program" with example data ? Thanks

```
$ ./hyperhotp help
Usage: ./hyperhotp program <8-character serial number> <40-character hex seed> <whether to generate 6-character (false) or 8-character (true) HOTP codes>

```

**Comment by casept** [comment] 2021-06-07 21:19
I've just committed a small change that actually logs the error libusb produces in that spot.

The argument format is pretty much the same as the Windows utility (just specified on the CLI rather than in an interactive menu), so running 

```shell
./hyperhotp program 87654321 abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd true
```

would program the HOTP secret `abcdabcdabcdabcdabcdabcdabcdabcdabcdabcd` (in the 40-digit hex format) with the serial number `87654321` that generates 8-digit codes (that's what the `true` stands for).

The 40-digt secret should be provided by whatever you're authenticating against. Sometimes the secret is provided as a 20-character ASCII string instead, which is trivial to convert to the hex format but not yet implemented by this tool. Let me know if you need it and I'll try to implement it.

**Comment by grigio** [comment] 2021-06-07 21:39
Thanks it works!
I just wanted to try to backup my fido key to another one. It seems https://webauthn.io asks another pin even if the secret data is the same

**Comment by grigio** [comment] 2021-06-07 21:43
Are you able to use Hyperfido with OpenSSH ? It seems it isn't supported https://github.com/Yubico/libfido2/issues/238

**Comment by casept** [comment] 2021-06-07 21:44
Happy to hear that it worked for you!

Nope, I haven't managed to get SSH to work either. Not even the mode where the actual key isn't stored on the device. I've also tried several different ciphers.

**Closed as completed** 2021-06-08 07:16 UTC
